# Generated by Django 4.1 on 2022-08-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
